# Generated by Django 4.1 on 2023-04-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Q_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirements',
            old_name='deptid',
            new_name='client_id',
        ),
    ]
