# Generated by Django 4.1 on 2023-04-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Q_app', '0002_rename_deptid_requirements_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirements',
            old_name='client_id',
            new_name='clientid',
        ),
    ]
