# Generated by Django 4.1.6 on 2023-03-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Q_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='password',
            field=models.CharField(max_length=4000),
        ),
    ]
